[package]
name = "lowdash"
version = "0.8.0"
authors = ["Tirtadwipa Manunggal <tirtadwipa.manunggal@gmail.com>"]
description = "A highly optimized utility library inspired by Lodash for Rust with zero dependencies"
repository = "https://github.com/liberocks/lowdash"
readme = "README.md"
license = "MIT"
categories = ["rust-patterns"]
keywords = ["rust-lodash", "lodash", "utility"]
edition = "2021"
autobenches = false

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
