name: Coverage
on:
  push:
    branches:
      - "**"
permissions:
  contents: read
  id-token: write
env:
  RUST_BACKTRACE: 1
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - nightly
        target:
          - x86_64-unknown-linux-gnu
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config zlib1g-dev
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: coverage
        run: |
          mkdir -p coverage
          cargo llvm-cov --workspace --lcov --output-path coverage/lcov.info --ignore-filename-regex '(^|/)benches/'
      - name: Report coverage to DeepSource
        run: |
          curl -fsSL https://cli.deepsource.com/install | BINDIR=./bin sh
          ./bin/deepsource report --analyzer test-coverage --key rust --value-file coverage/lcov.info --use-oidc
